server:
  port: '@server.port@'

management:
  security:
    flag: false
  server:
    port: '@management.port@'
  metrics:
    export:
      statsd:
        flavor: etsy
        enabled: false
      prometheus:
        enabled: false
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

spring:
  application:
    name: '@project.name@'
  output:
    ansi:
      enabled: always
info:
  version: '@project.version@'
  stage: dev

service:
  invoicing:
    url: http://hellgate:8022/v1/processing/invoicing
    networkTimeout: 5000
  withdrawal:
    url: http://hellgate:8022/v1/processing/invoicing
    networkTimeout: 5000
  wallet:
    url: http://hellgate:8022/v1/processing/invoicing
    networkTimeout: 5000
  destination:
    url: http://hellgate:8022/v1/processing/invoicing
    networkTimeout: 5000

kafka:
  bootstrap.servers: "localhost:29092"
  num-stream-threads: 7
  stream:
    retries-attempts: 300
    retries-backoff-ms: 1000
  ssl:
    enable: false
    keystore-location: src/main/resources/cert/kenny-k.struzhkin.p12
    keystore-password: kenny
    key-password: kenny
    server-password: kenny12
    server-keystore-location: src/main/resources/cert/truststore.p12
  topic:
    source:
      invoicing: mg-event
      withdrawal: mg-withdrawal
    sink:
      payment: payment
      refund: refund
      chargeback: chargeback
      withdrawal: withdrawal

stream:
  withdrawal:
    debug: false
